//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajMvc.Models.EntityFramework
{
    using System;
    using System.Collections;
    using System.Collections.Generic;

    public partial class Sepet 
    {
        public int Id { get; set; }
        public string sepetyemek { get; set; }
        public Nullable<int> sepetfiyat { get; set; }
        public Nullable<int> sepetadet { get; set; }
        public Nullable<int> sepettutar { get; set; }

      
    }
}
